[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_dir = "cache"
solc_version = "0.8.20"

optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/ezdslNh_nZf8ZrQQ9oyPr"
base-mainnet = "https://base-mainnet.g.alchemy.com/v2/ezdslNh_nZf8ZrQQ9oyPr"

[etherscan]
base-sepolia = { key = "XW684YB6Z7A7Q4HYCUNJ65INXA62G9Q81A" }
base = { key = "XW684YB6Z7A7Q4HYCUNJ65INXA62G9Q81A" }